Blazor Server setup & data model DDL
KarmaKamikaze/P7-Project pull request #10
Opened 2023-10-12 10:49 UTC by damniko

2023-10-13 11:43 UTC, KasperHenningsen requested changes

2023-10-13 11:43 UTC, KasperHenningsen commented on ChatRPG/ChatRPG/Areas/Identity/Pages/Account/_ViewImports.cshtml
> +@using ChatRPG.Areas.Identity.Pages.Account
Pls fix
```suggestion
@using ChatRPG.Areas.Identity.Pages.Account

```

2023-10-13 11:43 UTC, KasperHenningsen commented on ChatRPG/ChatRPG/Data/Models/AbilityType.cs
> +}
```suggestion
}

```

2023-10-13 11:43 UTC, KasperHenningsen commented on ChatRPG/ChatRPG/Data/Models/CharacterType.cs
> +}
```suggestion
}

```

2023-10-13 11:43 UTC, KasperHenningsen commented on ChatRPG/ChatRPG/Data/Models/EventType.cs
> +}
```suggestion
}

```

2023-10-13 11:43 UTC, KasperHenningsen commented on ChatRPG/ChatRPG/Data/Models/ModifierType.cs
> +}
```suggestion
}

```

2023-10-13 11:43 UTC, KasperHenningsen commented on ChatRPG/ChatRPG/Properties/serviceDependencies.json
> +}
```suggestion
}

```

2023-10-13 11:43 UTC, KasperHenningsen commented on ChatRPG/ChatRPG/Properties/serviceDependencies.local.json
> +}
```suggestion
}

```

2023-10-13 11:43 UTC, KasperHenningsen commented on ChatRPG/ChatRPG/wwwroot/css/open-iconic/ICON-LICENSE
> +THE SOFTWARE.
```suggestion
THE SOFTWARE.

```

2023-10-13 11:48 UTC, KasperHenningsen approved these changes

2023-10-16 11:34 UTC, Sarmisuper requested changes
Du mangler lige at comitte de ændringer vi snakkede om

2023-10-16 14:42 UTC, Sarmisuper approved these changes

2023-10-16 14:47 UTC, KasperHenningsen approved these changes

2023-10-16 14:52 UTC, KarmaKamikaze approved these changes

2023-10-16 15:05 UTC, mirakst requested changes
looks good, jeg har tilføjet en enkelt suggestion fordi pattern matching er cool og læsbart og det desuden trækker death ud i en metode så det kan processes der

2023-10-16 15:08 UTC, KarmaKamikaze commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
Haskell om nattøøøønn!

CharacterDeath er nok en event.

2023-10-16 15:13 UTC, mirakst commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
> Haskell om nattøøøønn!
> 
> CharacterDeath er nok en event.

Så kan vi bare raise den event fra metoden der :D Det er vel en implementationsdetalje, idéen var bare at trække det ud fordi det nok bliver lidt mere kompliceret end bare at sætte en oneliner

2023-10-16 15:14 UTC, Sarmisuper commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
Er du sikker på det her er equivalent? Hvis newhealth er 0 her, så bliver værdien bare newhealth, selvom at Characterdeath burde trigger.

2023-10-16 15:17 UTC, Sarmisuper commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
eller, det problem ville også opstå i dams version. Jeg tager mit approval tilbage!

2023-10-16 15:22 UTC, damniko commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
forstår hverken pattern matching eller din kommentar @Sarmisuper

2023-10-16 15:22 UTC, mirakst commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
> Er du sikker på det her er equivalent? Hvis newhealth er 0 her, så bliver værdien bare newhealth, selvom at Characterdeath burde trigger.

ved ikke hvad du snakker om...
*opdaterer suggestion i smug*

2023-10-16 15:22 UTC, Sarmisuper commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
mikkels version, men med > istedet for >= der ved comparison med 0 burde virke

2023-10-16 15:29 UTC, mirakst commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
> forstår hverken pattern matching eller din kommentar @Sarmisuper

vi laver et pair (value, _currentHealth + value)
så laver vi en switch hvor vi evaluater expressions oppefra og tager første match
så renamer eller discarder vi værdier i vores pair

e.g. case 1 hvor _currentHealth + value <= maxHealth og > 0:
vi renamer _currentHealth + value til newHealth (bruges også i expression der matches på), og sætter _currentHealth til newHealth

det er funktionel programmering

2023-10-16 15:29 UTC, Sarmisuper commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
> nåh, det er fordi jeg har misforstået min egen funktion - den skal bare sætte værdien, ikke lægge noget til den eksisterende. @mirakst jeg er ikke overbevist om at det er mere læsbart, det må være op til _the others_

Nej, tror ikke det er det der er galt. Det er fordi at din chain af if-elses kommer i forkert rækkefølge. Byt om på <=0 comparisonen og <= MaxHealth comparisonen.

2023-10-16 15:30 UTC, damniko commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
@Sarmisuper @mirakst kom igen nu

2023-10-16 15:32 UTC, Sarmisuper commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
Nååh du snakker om at man ikke skal sammenligne summen af currenthealth og value, men bare value. Altså at value ikke er damagen spilleren tager, men spilleren potential nye hp værdi? Det har du nok ret i, men du skal stadig bytte om på dine if-else conditions

2023-10-16 15:35 UTC, Sarmisuper commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +            }
Jaaa, ville det ikke være bedre med <= ?

2023-10-16 15:37 UTC, Sarmisuper commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
Altså det giver mening at value er den nye potential hp og ikke den skade spilleren tager. For at invoke setteren skriver man jo Health = 10. Og ift == så er jeg enig

2023-10-16 15:41 UTC, damniko commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
@mirakst @Sarmisuper kom igen igen

2023-10-16 15:43 UTC, mirakst commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
looks good to me
sorry for nitpick

2023-10-16 15:44 UTC, Sarmisuper approved these changes
lgtm

2023-10-16 18:27 UTC, damniko commented on ChatRPG/ChatRPG/Data/Models/Character.cs
> +    }
@mirakst det skal du ikke beklage, det gjorde at vi fik løst et problem (og jeg blev opmærksom på at pattern matching er en ting)!

2023-10-16 18:28 UTC, merged

2023-10-16 18:29 UTC, damniko commented
@selectionator jeg har merget denne da den er blevet extensively reviewet af de andre, men det er nok stadig en god idé at du lige kigger det igennem og siger til hvis der er noget du undrer dig over